### ISSUE TITLE
wallpaper >-<

### ISSUE THREAD

**Issue by Selphy1337** [nuxshed/dotfiles#10]
yo this rice pretty af but i cant find the wallpaper :(
mind giving it to me? id be verry thankfull fr ily ong

**Comment by nuxshed** [comment]
sorry for the late reply...
[here you go](https://thebookblossom.files.wordpress.com/2018/05/cropped-7c1eb9c32c5ff022a0bb91b5da91f792.jpg)

**Comment by Selphy1337** [comment]
thanks! love u
