### ISSUE TITLE
awesome bar shows on only one screen

### ISSUE THREAD

**Issue by iuliandita** [nuxshed/dotfiles#2]
I was trying out your awesome config, and the bar only shows on screen 1, while the taglist and tasklist control items on screen 2.
Any idea what might be wrong here?
Running on Arch, with awesome-git (v4.3-1336).

**Comment by nuxshed** [comment]
@iuliandita Does it work after 44c4a31?

**Comment by iuliandita** [comment]
🤗 that did it, thanks! I kinda figured out the change in `tasklist.lua`, but not the one in `init.lua`.
Great work you did here, btw! And thank you for the quick reply and fix!
Happy New Year!

**Comment by nuxshed** [comment]
Happy New Year to you too!
and thank you for reporting this!
