### ISSUE TITLE
Installation guide?

### ISSUE THREAD

**Issue by FinleyVickers** [nuxshed/dotfiles#3]
There does not appear to be an installation guide in the wiki. I see it referenced multiple times in the reddit thread, so I'm unsure if I'm just being dumb, or if something else happened.

**Comment by nuxshed** [comment]
There was an installation guide in the wiki for nixos users, but i ended up removing it as it takes a lot of changing stuff (usernames, gpg keys, hostnames, etc.) to properly set it up.

So, I've decided to remove the installation guide until I can set up a system which manages all those things.

edit:
if you just want the awesome config:
copy the `config/awesome` folder over to `~/.config/awesome`
clone bling and layout-machi into `~/.config/awesome/modules`
and copy `secrets-sample.lua` to `secrets.lua` (edit if if you need)

**Comment by gfsd3v** [comment]
@nuxshed anyway I could have access to the old wiki content about NixOs? I want to give it a try to get it up and running for me, I think it would a great starter point to migrating my daily driver to NixOs
