### ISSUE TITLE
Coffe Backstory

### ISSUE THREAD

**Issue by DenverEllis** [nuxshed/dotfiles#5]
I need some context/backstory on the bin/coffe script... If it is exactly what I think it is, I need some insider knowledge for my imagination to play with because that would just be too cool.

**Comment by nuxshed** [comment]
i got it off of a gist by xero (can't find that link rn)

they seem to have played with that idea a bit more, and made more animated terminal art
https://github.com/xero/dotfiles/blob/master/fun/bin/food
