### ISSUE TITLE
i need help god damn

### ISSUE THREAD

**Issue by ghost** [nuxshed/dotfiles#6]
i'm sorry how do i install this jesus damn plase help

**Comment by EpsilonKu** [comment]
On NixOS?

**Comment by ghost** [comment]
on arch if possible

**Comment by EpsilonKu** [comment]
Just copy configs. What configs do you want? Awesome WM, Neovim?

**Comment by nuxshed** [comment]
the ones in `config/` should all work indpendently iirc,
just copy over whatever you want into the proper place.

if you just want the awesomewm config,
copy `config/awesome` over to `~/.config/awesome`
