### ISSUE TITLE
i don't know anything about how to copy dotfiles and also how to apply it can anyone help me

### ISSUE THREAD

**Issue by Bhavya031** [nuxshed/dotfiles#8]
i copied config files in .config folder also i copied  bin to bin folder, but i have no idea that what should i do with hosts and modules file.https://imgur.com/a/TDXIP4b

**Comment by EpsilonKu** [comment]
Are you sure that you on git version of awesome?

**Comment by Bhavya031** [comment]
> Are you sure that you on git version of awesome?

Yes,I'm sure that it's git version of awesome .
